[package]
name = "energonsoftware"
version = "0.1.0"
authors = ["Shane Lillie <ignignokterr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
dynamodb_expression = { git = "https://github.com/Luminoth/dynamodb_expression", default-features = false, features = ["rustls"] }
dynomite = { version = "0.10", default-features = false, features = ["rustls"] }
rusoto_core = { version = "0.45", default-features = false, features = ["rustls"] }
rusoto_dynamodb = { version = "0.45", default-features = false, features = ["rustls"] }
